axe-name: "Insomniac Axe"
gui:
  lines: 3
  title: "&aEnchants Shop"
pumpkin-top:
  format: "&3{0} --> {1}" #0 is the name of player and 1 is the balance
  size: 5 #how many players in the list

levels:
  1:
    booster: 0.10
    blocksToNextLevel: 1000
  2:
    booster: 0.20
    blocksToNextLevel: 2000
enchants:
  autosell:
    name: "&4autosell"
    enabled: true
    slot: 10
    item: GOLD
    glow: true
    price: 100
    lore:
      - "&3Price: 100"
      - "selling automatically blocks"
  zeus:
    name: "&3Zeus"
    enabled: true
    slot: 12
    item: POTATO
    percentage: 10 #10%
    glow: true
    price: 1000
    lore:
      - "&3Price: 1000"
      - "&4It will give you the imaginary power of zeus"
  speed:
    name: "&cSpeed"
    enabled: true
    slot: 14
    item: SUGAR
    glow: true
    price: 100
    lore:
      - "&3Price: 100"
      - "Speed while holding"
  haste:
    name: "&aHaste"
    enabled: true
    slot: 16
    item: GOLDEN_AXE
    glow: true
    price: 100
    lore:
      - "&3Price: 100"
      - "Haste while holding"
  destroyer:
    name: "&4Destroyer"
    enabled: true
    slot: 18
    item: ACACIA_BUTTON
    glow: false
    price: 100
    lore:
      - "&3Price: 100"
      - "Destroy blocks..."
  doubledrops:
    name: "&4Double Drops"
    enabled: true
    slot: 20
    item: DIAMOND
    glow: true
    price: 200
    lore:
      - "&3Price: 200"
      - "Double drops each time"